name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Generate the Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Berghtx
          outputs: |
            ./output/snake.svg
          palette: github-dark

      - name: Remove white background from snake.svg
        run: |
          sed -i '/<rect.*fill="#fff".*\/>/d' ./output/snake.svg
          sed -i '/<rect.*fill="white".*\/>/d' ./output/snake.svg

      - name: Commit and push the animation
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Berghtx
          author_email: bernardogomes146@gmail.com
          message: "Generate snake animation"
