name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # executa todos os dias à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate the snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: berghtx
          outputs: |
            ./output/snake.svg

      - name: Push the generated snake.svg to the output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate snake animation"
